# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Çözüm dosyasını ve bağımlılıkları kopyala
COPY MonitoringControlSystem.sln ./
COPY Controllers/Controllers.csproj ./Controllers/
COPY Interfaces/Interfaces.csproj ./Interfaces/
COPY Models/Models.csproj ./Models/
COPY MonitoringControlSystem.Domain/MonitoringControlSystem.Domain.csproj ./MonitoringControlSystem.Domain/
COPY MonitoringControlSystem/MonitoringControlSystem.csproj ./MonitoringControlSystem/
COPY MonitoringControlSystemApplication/MonitoringControlSystemApplication.csproj ./MonitoringControlSystemApplication/
COPY MonitoringControlSystemInfrastructure/MonitoringControlSystemInfrastructure.csproj ./MonitoringControlSystemInfrastructure/
COPY Services/Services.csproj ./Services/

# Bağımlılıkları yükle
RUN dotnet restore

# Kaynak kodları kopyala ve build et
COPY . .
WORKDIR /app/MonitoringControlSystem
RUN dotnet publish -c Release -o /app/publish

# Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Uygulama çalıştırma
ENTRYPOINT ["dotnet", "MonitoringControlSystem.dll"]
