# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Projeleri kopyala ve bağımlılıkları yükle
COPY *.sln ./
COPY Controllers/Controllers.csproj ./Controllers/
COPY Interfaces/Interfaces.csproj ./Interfaces/
COPY Models/Models.csproj ./Models/
COPY MonitoringControlSystem.Domain/MonitoringControlSystem.Domain.csproj ./MonitoringControlSystem.Domain/
COPY MonitoringControlSystem/MonitoringControlSystem.csproj ./MonitoringControlSystem/
COPY MonitoringControlSystemApplication/MonitoringControlSystemApplication.csproj ./MonitoringControlSystemApplication/
COPY MonitoringControlSystemInfrastructure/MonitoringControlSystemInfrastructure.csproj ./MonitoringControlSystemInfrastructure/
COPY Services/Services.csproj ./Services/

# Restore işlemi
RUN dotnet restore

# Kaynak kodları kopyala ve derle
COPY . .
WORKDIR /app/MonitoringControlSystem
RUN dotnet publish -c Release -o /app/publish

# Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MonitoringControlSystem.dll"]
